name: Create S3 Bucket

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your desired AWS region

      - name: Delete S3 bucket
        run: |
           aws s3 rb s3://githubactiontacs --force     
#          aws s3api create-bucket --bucket githubactiontacs --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1
