name: githubs3bucket

on:
  push:
    branches:
      - main
jobs: 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@main
  - name: Upload to s3
    run: |
      aws s3 mb s3://githubaction_tacs
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}   
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}   


     
