name: GitHub Secrets

on:
  workflow_dispatch:

environment:


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:  
      - name: Print Secret
        run: |
            echo "MY_SECRET: ${{ secrets.MY_SECRET  }}"
            echo "i_dont_exist: ${{ secrets.i_dont_exist  }}"
            
      - name: Print Secret as an environment variable
        run: |
            echo "MY_SECRET: $MY_SECRET"
        env:
            MY_SECRET: ${{ secrets.MY_SECRET }}
